#!/bin/bash

function rand_wait
{
    local low=$1  # miliseconds
    local high=$2 # miliseconds
    local rv=`bc <<< "scale=4; $[($RANDOM % ($high - $low)) + $low] / 1000"`
    echo "0$rv"
}

function linebreak
{
    echo -ne "\n"
}

# params:
#   $1: Sring to be printed
#   $2: Wait time at the end of the line (optional)
#   $3: Number of line breaks at the end (optional)
function typewriter_echo
{
    string="$1"
    while test -n "$string"; do
        c=${string:0:1}
        echo -ne "$c"
        if [ "$c" == " " ]; then
            sleep 0.07
        elif [ "$c" == "." ] || [ "$c" == "?" ]; then
            sleep 0.05
        else
            sleep 0.05
        fi
        string=${string:1}
    done

    if [ -n "$2" ]; then
        sleep `bc <<<"scale=4; ($2 / 4) * 3"`
    fi

    line_size="1"
    if [ -n "$3" ]; then
        line_size="$3"
    fi

    for n in `seq 1 $line_size`; do
        linebreak
    done

    if [ -n "$2" ]; then
        sleep `bc <<<"scale=4; ($2 / 4)"`
    fi
}

function set_autologin_user
{
    sed -i "s/\(1:2345:respawn:\).\+\$/\1\/sbin\/getty -a $1 38400 tty1/" \
        /etc/inittab
}

function enable_autostart
{
    sed -i "s/^\(ENABLED\=\)[01]$/\11/" /etc/profile.d/autostart-kano-init.sh
}

function disable_autostart
{
    sed -i "s/^\(ENABLED\=\)[01]$/\10/" /etc/profile.d/autostart-kano-init.sh
}

function get_option
{
    while true; do
        read -e option
        eval "$1=$option"
        if [ -z "$option" ]; then
            typewriter_echo "You need to choose one option. Which one do you pick:"
        elif [ -z "`grep "^[123]$" <<<"$option"`" ]; then
            typewriter_echo "The options are 1, 2, or 3. Which one do you pick:"
        else
            break
        fi
    done
}

# Check for root priviledges.
if [ `id -u` -ne 0 ]; then
    echo "kano-init must be executed with root privileges"
    exit 1
fi

# Special case: With the 'autostart' argument, kano-init will set up
# to be executed during the next reboot
if [ "$1" == "reset" ]; then
    set_autologin_user "root"
    enable_autostart
    echo "kano-init scheduled for the next system reboot"
    exit 0
fi

# Get the resources directory
if [ -d "ascii_art" ]; then
    res_dir="."
else
    res_dir="/usr/share/kano-init/"
fi

# Disable Ctrl+C and Ctrl+D in the console
stty intr undef
stty eof '?'

clear
sleep 1

typewriter_echo "Hello!" 0.5
typewriter_echo "I'm Kano. Thanks for bringing me to life." 0.5 2
typewriter_echo "What's your name?"

# Read the username
while true; do
    read -e username
    if [ -z "$username" ]; then
        typewriter_echo "I need to know your name:"
    elif [ -z "`grep "^[a-zA-Z0-9]\+$" <<<"$username"`" ]; then
        typewriter_echo "Only letters and numbers are allowed. Pick another one:"
    else
        break
    fi
done

# Get the username of the user with UID=1000
old_user=`grep "^[^:]*:[^:]*:1000:1000" /etc/passwd | awk -F ':' '{ print $1 }'`
if [ -n "$old_user" ]; then
    # Change both the user group names and move home dir
    usermod -l "$username" -d "/home/$username" -m "$old_user" 2>/dev/null
    groupmod -n "$username" "$old_user" 2>/dev/null

    # Rename the 'Home' desktop icon
    sed -i "s/^\(Name\(\[.\+\]\)\?\)\=.*$/\1=$username/" \
           "/home/$username/Desktop/Home"
else
    # TODO: We might create the user in this case
    echo "Error: No user with UID=1000 found."
    exit 1
fi

# Setup automatic login for this user on any subsequent reboot
set_autologin_user "$username"
disable_autostart

echo -ne "\n"
typewriter_echo "$username, follow the white rabbit... " 1 0
typewriter_echo "If you dare." 0.5 2
typewriter_echo "But first, I bet I can out-think you..." 0.5 2

while true; do
    typewriter_echo "Pick a type:" 0.1
    typewriter_echo "  1) Animal" 0.1
    typewriter_echo "  2) Plant" 0.1
    typewriter_echo "  3) Machine" 0.1 2
    typewriter_echo "Your choice:"
    get_option "picked_type"
    linebreak

    typewriter_echo "Pick a size:" 0.1
    typewriter_echo "  1) Big" 0.1
    typewriter_echo "  2) Medium" 0.1
    typewriter_echo "  3) Small" 0.1 2
    typewriter_echo "Your choice:"
    get_option "picked_size"
    linebreak

    ascii_art_dir="$res_dir/ascii_art"
    case "$picked_type$picked_size" in
        11) cat "$ascii_art_dir/elephant.txt" ;;
        12) cat "$ascii_art_dir/human.txt" ;;
        13) cat "$ascii_art_dir/rabbit.txt" ;;
        21) cat "$ascii_art_dir/tree.txt" ;;
        22) cat "$ascii_art_dir/potato-head.txt" ;;
        23) cat "$ascii_art_dir/flower.txt" ;;
        31) cat "$ascii_art_dir/car.txt" ;;
        32) cat "$ascii_art_dir/robot.txt" ;;
        33) cat "$ascii_art_dir/chip.txt" ;;
    esac
    linebreak

    if [ "$picked_type$picked_size" -eq 13 ]; then
        typewriter_echo "You win..." 0.5 2
        break
    else
        typewriter_echo "Computers rule! Try again." 0.5 2
    fi
done

typewriter_echo "I'm good at remembering and combining things." 0.5
typewriter_echo "But, I need humans to help me make new things." 0.5 2
typewriter_echo "I'm even smarter when I can talk to other computers on the Internet." 0.5
typewriter_echo "Lets hunt for the signal." 0.5

kwifiprompt.py
linebreak

typewriter_echo "Help me get a video from the Internet."
sudo -u "$username" -H bash --init-file $res_dir/subshellrc
clear

typewriter_echo "Uhoh!" 0.5
typewriter_echo "More awesome ASCII art! Booom!" 0.5
typewriter_echo "3 ... 2 ... 1 ..." 0.5
typewriter_echo "Quick, $username, type startx to escape!"

stty intr ^C
stty eof ^D

# Start the terminal as the new user
exec sudo -u "$username" -i -H bash
