bin/* usr/bin/
kano_feedback usr/lib/python2.7/dist-packages/
media usr/share/kano-feedback/

icon/Feedback /usr/share/kano-apps/extras
icon/feedback.png /usr/share/kano-apps/icons

kdesktop/Feedback.lnk /usr/share/kano-desktop/kdesk/kdesktop/
kdesktop/kano-feedback.desktop /usr/share/applications/
icon/feedback-desktop.png /usr/share/kano-desktop/icons
icon/feedback-hover.png /usr/share/kano-desktop/icons
